name: CI-Multi-Jobs

on:
  push:
    branches:
      - branch_name
  workflow_dispatch:

jobs:

  # without-checkout-job:
  #   name: Without Checkout
  #   runs-on: 'ubuntu-latest'
  #   steps:
  #     - name: Install tree & run
  #       run: |
  #         sudo apt-get install -y tree
  #         tree .
  checkout:
    name: With Checkout
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install tree & run
        run: |
          sudo apt-get install -y tree
          tree .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.15"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build

      - name: Build the package
        run: python -m build

      - name: Display directory tree after build
        run: tree







